version: "3.8"
services:
  mongo:
    image: mongo:7.0.5
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: data_with_mongodb
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init.js